apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

group = 'com.ritvik.jammusic.jarvis'
version = '0.1.0'

android {
    namespace 'com.ritvik.jammusic.jarvis'
    defaultConfig {
        versionCode 1
        versionName "0.1.0"
    }
}

repositories {
    mavenCentral()
    google()
    maven { url 'https://www.jitpack.io' }
}

dependencies {
    implementation "androidx.core:core-ktx:1.13.1"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0"
    implementation 'xyz.rementia:openwakeword:0.1.3'
}
