// Curated topic and difficulty sets. Each set has enough questions for a full
// ten-question match without repeats.
const rows = [
  // ANIME · EASY
  ['Anime','easy','What is the name of the electric mouse Pokémon?','Eevee|Pikachu|Jigglypuff|Psyduck',1],
  ['Anime','easy','Who is the main young ninja in Naruto?','Sasuke Uchiha|Naruto Uzumaki|Kakashi Hatake|Rock Lee',1],
  ['Anime','easy','Which anime features the Straw Hat Pirates?','Bleach|One Piece|Fairy Tail|Blue Lock',1],
  ['Anime','easy','What is the name of Goku’s young son?','Gohan|Trunks|Krillin|Piccolo',0],
  ['Anime','easy','In Demon Slayer, what is Tanjiro trying to do for Nezuko?','Find a cure|Make her a Hashira|Find a dragon|Teach her to cook',0],
  ['Anime','easy','Which studio made the film My Neighbor Totoro?','Pixar|Studio Ghibli|DreamWorks|MAPPA',1],
  ['Anime','easy','What kind of creature is Totoro?','A forest spirit|A robot|A dragon|A sea monster',0],
  ['Anime','easy','Which blue robotic cat comes from the future?','Doraemon|Hello Kitty|Pikachu|Anpanman',0],
  ['Anime','easy','What is Sailor Moon’s everyday name?','Usagi Tsukino|Mikasa Ackerman|Nami|Sakura Haruno',0],
  ['Anime','easy','Which sport is central to Haikyu!!?','Basketball|Volleyball|Football|Tennis',1],
  // ANIME · MEDIUM
  ['Anime','medium','What is the name of the notebook in Death Note?','Black Book|Death Note|Shinigami Scroll|Kira File',1],
  ['Anime','medium','Who is the captain of the Straw Hat crew?','Roronoa Zoro|Monkey D. Luffy|Sanji|Usopp',1],
  ['Anime','medium','In Fullmetal Alchemist, what do the Elric brothers seek?','A philosopher’s stone|A dragon egg|A magic sword|A lost crown',0],
  ['Anime','medium','What is the name of the school in My Hero Academia?','Tokyo Hero School|U.A. High School|Shinobi Academy|Soul Society',1],
  ['Anime','medium','Which character is known as the Flame Hashira in Demon Slayer?','Giyu Tomioka|Kyojuro Rengoku|Tengen Uzui|Muichiro Tokito',1],
  ['Anime','medium','Which team does Hinata join in Haikyu!!?','Nekoma|Karasuno|Aoba Johsai|Shiratorizawa',1],
  ['Anime','medium','In Naruto, what is the name of the village Naruto belongs to?','Hidden Sand|Hidden Leaf|Hidden Mist|Hidden Cloud',1],
  ['Anime','medium','Which anime follows a boy who becomes a State Alchemist?','Black Clover|Fullmetal Alchemist|Dr. Stone|Soul Eater',1],
  ['Anime','medium','What is the name of the giant wall-surrounded city in Attack on Titan?','The Shiganshina District|The Hidden Leaf|The Soul Society|The Grand Line',0],
  ['Anime','medium','Which Studio Ghibli film features a moving castle?','Kiki’s Delivery Service|Howl’s Moving Castle|Ponyo|The Cat Returns',1],
  // ANIME · DIFFICULT
  ['Anime','difficult','What is the name of the alchemy rule that governs equivalent exchange?','Equivalent Cost|Equivalent Exchange|Equal Return|Balanced Matter',1],
  ['Anime','difficult','In One Piece, what is the name of the cook in the Straw Hat crew?','Franky|Brook|Sanji|Jinbe',2],
  ['Anime','difficult','Which Pokémon type is super effective against Dragon in the main games?','Rock|Fairy|Bug|Steel',1],
  ['Anime','difficult','What is the name of the organization that employs Loid in Spy x Family?','WISE|SWORD|The Survey Corps|The League',0],
  ['Anime','difficult','In Spirited Away, what name does Yubaba give Chihiro?','Sen|Lin|Rin|Haku',0],
  ['Anime','difficult','Which sword style does Zenitsu primarily use?','Water Breathing|Thunder Breathing|Wind Breathing|Stone Breathing',1],
  ['Anime','difficult','What is the name of the powerful energy used by characters in Jujutsu Kaisen?','Spirit pressure|Cursed energy|Nen|Chakra',1],
  ['Anime','difficult','Which member of Team 7 is the team’s original sensei?','Iruka|Might Guy|Kakashi|Jiraiya',2],
  ['Anime','difficult','In Cowboy Bebop, what is the name of Spike Spiegel’s ship?','Swordfish II|Red Tail|Bebop|Hammerhead',2],
  ['Anime','difficult','Which kingdom is Asta from in Black Clover?','Spade Kingdom|Clover Kingdom|Heart Kingdom|Diamond Kingdom',1],

  // MOVIES · EASY
  ['Movies','easy','What is the name of Moana’s island home?','Motunui|Arendelle|Berk|Monstropolis',0],
  ['Movies','easy','Which film features a toys-owning boy named Andy?','Toy Story|Cars|Up|Coco',0],
  ['Movies','easy','In The Incredibles, what is the family surname?','Parr|Parker|Potter|Poppins',0],
  ['Movies','easy','In Finding Nemo, what kind of fish is Nemo?','Goldfish|Clownfish|Tuna|Swordfish',1],
  ['Movies','easy','Which superhero is also called the Dark Knight?','Superman|Batman|Thor|Iron Man',1],
  ['Movies','easy','What is the name of the kingdom in The Lion King?','Pride Lands|Neverland|Arendelle|Atlantis',0],
  ['Movies','easy','In The Wizard of Oz, what color is the brick road?','Yellow|Red|Blue|Green',0],
  ['Movies','easy','Which movie features a race car named Lightning McQueen?','Cars|Turbo|Planes|Speed Racer',0],
  ['Movies','easy','Who is the space ranger in Toy Story?','Woody|Buzz Lightyear|Rex|Forky',1],
  ['Movies','easy','Which Indian film series features the character Chulbul Pandey?','Dabangg|Dhoom|Golmaal|Don',0],
  // MOVIES · MEDIUM
  ['Movies','medium','What is the name of the fictional African nation in Black Panther?','Genovia|Wakanda|Zamunda|Sokovia',1],
  ['Movies','medium','In The Matrix, which pill does Neo take?','Blue|Red|Green|Yellow',1],
  ['Movies','medium','Who directed Jurassic Park (1993)?','James Cameron|Steven Spielberg|George Lucas|Ridley Scott',1],
  ['Movies','medium','What is the name of the ship in Titanic?','Olympic|Titanic|Britannic|Carpathia',1],
  ['Movies','medium','In Coco, what is Miguel’s family trade?','Baking|Shoemaking|Fishing|Pottery',1],
  ['Movies','medium','Which actor played Jack Sparrow in Pirates of the Caribbean?','Orlando Bloom|Johnny Depp|Jude Law|Hugh Jackman',1],
  ['Movies','medium','What is the name of the hotel in The Shining?','Bates Motel|Overlook Hotel|Grand Budapest|Continental',1],
  ['Movies','medium','In Avatar (2009), what is the name of the moon where the story takes place?','Pandora|Endor|LV-426|Arrakis',0],
  ['Movies','medium','Which film follows a rat named Remy who wants to be a chef?','Ratatouille|Flushed Away|The Menu|Chef',0],
  ['Movies','medium','In the original Star Wars trilogy, who is Luke Skywalker’s sister?','Leia|Padmé|Rey|Jyn',0],
  // MOVIES · DIFFICULT
  ['Movies','difficult','Which film won the first Academy Award for Best Animated Feature?','Toy Story|Shrek|Monsters, Inc.|Spirited Away',1],
  ['Movies','difficult','Who composed the main score for the film Jaws?','John Williams|Hans Zimmer|Danny Elfman|Ennio Morricone',0],
  ['Movies','difficult','What is the name of the planet in Dune ruled by House Atreides?','Caladan|Arrakis|Giedi Prime|Salusa Secundus',1],
  ['Movies','difficult','In The Lord of the Rings, what is the name of Aragorn’s sword after it is reforged?','Glamdring|Andúril|Sting|Narsil',1],
  ['Movies','difficult','Which 1950 film introduced the character of Cinderella in Disney animation?','Cinderella|Sleeping Beauty|Pinocchio|Alice in Wonderland',0],
  ['Movies','difficult','Who directed the Japanese film Seven Samurai?','Yasujirō Ozu|Akira Kurosawa|Hayao Miyazaki|Kenji Mizoguchi',1],
  ['Movies','difficult','Which actor portrayed the title character in the 2000 film Gladiator?','Russell Crowe|Joaquin Phoenix|Eric Bana|Gerard Butler',0],
  ['Movies','difficult','In The Godfather, what is the family’s surname?','Soprano|Corleone|Capone|Barzini',1],
  ['Movies','difficult','Which Indian director made the film Pather Panchali?','Satyajit Ray|Raj Kapoor|Guru Dutt|Bimal Roy',0],
  ['Movies','difficult','What is the name of the artificial intelligence in 2001: A Space Odyssey?','HAL 9000|GERTY|JARVIS|Mother',0],

  // SONGS · EASY
  ['Songs','easy','Who sang the hit song “Shape of You”?','Ed Sheeran|Bruno Mars|Shawn Mendes|Justin Bieber',0],
  ['Songs','easy','Which band released “Hey Jude”?','The Rolling Stones|The Beatles|Queen|ABBA',1],
  ['Songs','easy','Who is known as the “King of Pop”?','Elvis Presley|Michael Jackson|Prince|Stevie Wonder',1],
  ['Songs','easy','Which singer released the album 1989?','Adele|Taylor Swift|Katy Perry|Rihanna',1],
  ['Songs','easy','Which group sang “Dancing Queen”?','ABBA|Queen|Boney M.|Bee Gees',0],
  ['Songs','easy','“Jai Ho” was featured in which film?','Lagaan|Slumdog Millionaire|3 Idiots|Dangal',1],
  ['Songs','easy','Who sang “Blinding Lights”?','The Weeknd|Drake|Post Malone|Bruno Mars',0],
  ['Songs','easy','Which instrument is played by blowing across a small mouth hole?','Flute|Cello|Drum kit|Harp',0],
  ['Songs','easy','Who sang the song “Roar”?','Lady Gaga|Katy Perry|Dua Lipa|Ariana Grande',1],
  ['Songs','easy','Which Indian singer is known for the song “Tum Hi Ho”?','Arijit Singh|Sonu Nigam|Udit Narayan|Mohit Chauhan',0],
  // SONGS · MEDIUM
  ['Songs','medium','Which artist released the album Thriller?','Prince|Michael Jackson|Lionel Richie|David Bowie',1],
  ['Songs','medium','Who originally recorded “I Will Always Love You” before it became a Whitney Houston hit?','Dolly Parton|Celine Dion|Aretha Franklin|Barbra Streisand',0],
  ['Songs','medium','Which band recorded the album Rumours?','Fleetwood Mac|Eagles|The Police|Journey',0],
  ['Songs','medium','Who sang the theme song “My Heart Will Go On” for Titanic?','Celine Dion|Mariah Carey|Whitney Houston|Shania Twain',0],
  ['Songs','medium','Which composer created the Four Seasons concertos?','Bach|Vivaldi|Mozart|Beethoven',1],
  ['Songs','medium','“Bohemian Rhapsody” was recorded by which band?','The Who|Queen|Pink Floyd|Led Zeppelin',1],
  ['Songs','medium','Which singer released “Rolling in the Deep”?','Adele|Amy Winehouse|Duffy|Lily Allen',0],
  ['Songs','medium','Who composed the song “Vande Mataram”?','Rabindranath Tagore|Bankim Chandra Chattopadhyay|Sarojini Naidu|Kazi Nazrul Islam',1],
  ['Songs','medium','Which artist is the lead singer of the band Coldplay?','Chris Martin|Thom Yorke|Bono|Chris Cornell',0],
  ['Songs','medium','Which Indian composer created the score for Slumdog Millionaire?','A. R. Rahman|Pritam|Shankar–Ehsaan–Loy|Ravi Shankar',0],
  // SONGS · DIFFICULT
  ['Songs','difficult','Which composer wrote the opera The Magic Flute?','Mozart|Verdi|Puccini|Handel',0],
  ['Songs','difficult','What was the title of the first Beatles album released in the UK?','Help!|Please Please Me|With the Beatles|A Hard Day’s Night',1],
  ['Songs','difficult','Which singer’s backing band was called the Revolution?','David Bowie|Prince|Bruce Springsteen|Madonna',1],
  ['Songs','difficult','Who wrote the lyrics for the musical Hamilton?','Lin-Manuel Miranda|Stephen Sondheim|Andrew Lloyd Webber|Jason Robert Brown',0],
  ['Songs','difficult','Which jazz musician recorded the album Kind of Blue?','Miles Davis|John Coltrane|Herbie Hancock|Louis Armstrong',0],
  ['Songs','difficult','Which composer wrote the ballet The Rite of Spring?','Igor Stravinsky|Claude Debussy|Sergei Rachmaninoff|Pyotr Tchaikovsky',0],
  ['Songs','difficult','Who was the lead vocalist of the band Nirvana?','Eddie Vedder|Kurt Cobain|Chris Cornell|Layne Staley',1],
  ['Songs','difficult','Which Indian classical instrument is Ravi Shankar famous for playing?','Sitar|Sarod|Tabla|Veena',0],
  ['Songs','difficult','Which band released the album The Dark Side of the Moon?','Genesis|Pink Floyd|Yes|The Moody Blues',1],
  ['Songs','difficult','Which singer-songwriter wrote “Both Sides, Now”?','Joni Mitchell|Carole King|Joan Baez|Diana Ross',0],

  // GENERAL KNOWLEDGE · EASY
  ['General Knowledge','easy','How many days are in a week?','Five|Six|Seven|Eight',2],
  ['General Knowledge','easy','What is the capital of France?','Rome|Paris|Lisbon|Vienna',1],
  ['General Knowledge','easy','Which planet do we live on?','Mars|Earth|Venus|Jupiter',1],
  ['General Knowledge','easy','How many sides does a triangle have?','Two|Three|Four|Five',1],
  ['General Knowledge','easy','Which language is primarily spoken in Brazil?','Spanish|Portuguese|French|Italian',1],
  ['General Knowledge','easy','What is the largest animal on Earth?','Elephant|Blue whale|Giraffe|Polar bear',1],
  ['General Knowledge','easy','Which country is famous for the Great Wall?','China|Japan|India|Thailand',0],
  ['General Knowledge','easy','What is the capital city of Italy?','Milan|Rome|Naples|Venice',1],
  ['General Knowledge','easy','Which month comes after April?','March|May|June|July',1],
  ['General Knowledge','easy','How many players from one team are on a soccer field at the start?','Nine|Ten|Eleven|Twelve',2],
  // GENERAL KNOWLEDGE · MEDIUM
  ['General Knowledge','medium','What is the currency of Japan?','Won|Yen|Yuan|Ringgit',1],
  ['General Knowledge','medium','Which city is nicknamed the “Eternal City”?','Athens|Rome|Cairo|Istanbul',1],
  ['General Knowledge','medium','How many squares are on a standard chessboard?','48|56|64|72',2],
  ['General Knowledge','medium','Which country gifted the Statue of Liberty to the United States?','France|Spain|Italy|Canada',0],
  ['General Knowledge','medium','What is the name of the line at zero degrees longitude?','Equator|Prime Meridian|Tropic of Cancer|International Date Line',1],
  ['General Knowledge','medium','Which author created the detective Hercule Poirot?','Arthur Conan Doyle|Agatha Christie|Dorothy Sayers|Ian Fleming',1],
  ['General Knowledge','medium','What is the official language of Egypt?','Arabic|French|Greek|Turkish',0],
  ['General Knowledge','medium','Which country hosted the first modern Olympic Games in 1896?','France|Greece|Italy|United Kingdom',1],
  ['General Knowledge','medium','What is the name of the world’s largest coral reef system?','Belize Barrier Reef|Great Barrier Reef|Red Sea Reef|New Caledonia Reef',1],
  ['General Knowledge','medium','Which Indian monument was built by Shah Jahan in memory of Mumtaz Mahal?','Red Fort|Taj Mahal|Qutub Minar|India Gate',1],
  // GENERAL KNOWLEDGE · DIFFICULT
  ['General Knowledge','difficult','Which treaty formally ended the First World War between Germany and the Allies?','Treaty of Paris|Treaty of Versailles|Treaty of Rome|Treaty of Utrecht',1],
  ['General Knowledge','difficult','What is the smallest country in the world by area?','Monaco|Vatican City|San Marino|Liechtenstein',1],
  ['General Knowledge','difficult','Which mathematician is associated with the incompleteness theorems?','Kurt Gödel|Alan Turing|John von Neumann|Blaise Pascal',0],
  ['General Knowledge','difficult','Which ancient library was located in Egypt?','Library of Pergamum|Library of Alexandria|House of Wisdom|Nalanda Library',1],
  ['General Knowledge','difficult','What is the deepest known point in Earth’s oceans?','Java Trench|Challenger Deep|Puerto Rico Trench|Milwaukee Deep',1],
  ['General Knowledge','difficult','Which country was formerly known as Abyssinia?','Eritrea|Ethiopia|Somalia|Sudan',1],
  ['General Knowledge','difficult','Who was the first person to reach the South Pole?','Ernest Shackleton|Roald Amundsen|Robert Falcon Scott|Fridtjof Nansen',1],
  ['General Knowledge','difficult','Which philosopher wrote The Republic?','Aristotle|Plato|Socrates|Epicurus',1],
  ['General Knowledge','difficult','What is the name of the world’s largest inland body of water?','Lake Superior|Caspian Sea|Lake Victoria|Aral Sea',1],
  ['General Knowledge','difficult','Which Indian mathematician is famous for work on infinite series and number theory?','Srinivasa Ramanujan|C. V. Raman|Homi Bhabha|Satyendra Nath Bose',0],

  // SCIENCE · EASY
  ['Science','easy','What gas do humans need to breathe to live?','Oxygen|Helium|Carbon dioxide|Hydrogen',0],
  ['Science','easy','How many legs does an insect have?','Four|Six|Eight|Ten',1],
  ['Science','easy','Which organ pumps blood through the body?','Lungs|Heart|Stomach|Kidneys',1],
  ['Science','easy','Which organ helps humans breathe by taking oxygen into the body?','Lungs|Stomach|Kidneys|Pancreas',0],
  ['Science','easy','What do caterpillars turn into?','Beetles|Butterflies or moths|Spiders|Ants',1],
  ['Science','easy','Which state of matter has a fixed shape and volume?','Solid|Liquid|Gas|Plasma',0],
  ['Science','easy','What is frozen water called?','Steam|Ice|Mist|Frosting',1],
  ['Science','easy','Which part of the body helps you think?','Heart|Brain|Liver|Lung',1],
  ['Science','easy','What force keeps planets in orbit around the Sun?','Gravity|Friction|Magnetism|Sound',0],
  ['Science','easy','What do plants use to make food from sunlight?','Photosynthesis|Digestion|Fermentation|Respiration only',0],
  // SCIENCE · MEDIUM
  ['Science','medium','What is the chemical symbol for gold?','Ag|Au|Gd|Go',1],
  ['Science','medium','Which part of a cell contains most of its genetic material?','Nucleus|Cell wall|Ribosome|Vacuole',0],
  ['Science','medium','What is the pH of pure water at room temperature, approximately?','3|5|7|10',2],
  ['Science','medium','Which blood type is often called the universal red-cell donor?','AB positive|O negative|A positive|B negative',1],
  ['Science','medium','What is the name of the process where a solid changes directly into a gas?','Condensation|Sublimation|Melting|Deposition',1],
  ['Science','medium','Which planet has the shortest year?','Mercury|Venus|Earth|Mars',0],
  ['Science','medium','What is measured in amperes?','Electric current|Temperature|Force|Luminous intensity',0],
  ['Science','medium','Which scientist formulated the three laws of motion?','Isaac Newton|Galileo Galilei|Albert Einstein|James Clerk Maxwell',0],
  ['Science','medium','What is the most abundant element in the universe?','Oxygen|Carbon|Hydrogen|Iron',2],
  ['Science','medium','Which vitamin is essential for normal blood clotting?','Vitamin A|Vitamin C|Vitamin D|Vitamin K',3],
  // SCIENCE · DIFFICULT
  ['Science','difficult','What is the SI unit of electric capacitance?','Henry|Farad|Tesla|Weber',1],
  ['Science','difficult','Which particle carries the strong nuclear force?','Photon|Gluon|W boson|Neutrino',1],
  ['Science','difficult','What is the approximate speed of light in a vacuum?','300,000 km/s|30,000 km/s|3,000 km/s|3,000,000 km/s',0],
  ['Science','difficult','Which molecule carries amino acids to the ribosome during protein synthesis?','mRNA|tRNA|rRNA|DNA polymerase',1],
  ['Science','difficult','What is the boundary around a black hole beyond which light cannot escape called?','Event horizon|Accretion disk|Singularity|Photon belt',0],
  ['Science','difficult','Which law states that entropy in an isolated system tends not to decrease?','First law of thermodynamics|Second law of thermodynamics|Ohm’s law|Hooke’s law',1],
  ['Science','difficult','What is the most common isotope of carbon?','Carbon-12|Carbon-13|Carbon-14|Carbon-16',0],
  ['Science','difficult','Which scientist proposed the uncertainty principle?','Niels Bohr|Werner Heisenberg|Erwin Schrödinger|Max Planck',1],
  ['Science','difficult','What is the name of the enzyme that unwinds DNA during replication?','Ligase|Helicase|Amylase|Catalase',1],
  ['Science','difficult','Which layer of Earth is liquid and generates most of its magnetic field?','Crust|Mantle|Outer core|Inner core',2],
];

module.exports = rows.map(([category, difficulty, prompt, choices, answerIndex], index) => ({
  id: `topic-${index + 1}`,
  category,
  difficulty,
  prompt,
  options: choices.split('|'),
  answerIndex,
}));
