// Offline question bank for Trivia Duel. Kept on the server so answers stay hidden
// until the player has answered. Questions are shuffled without repeats per match.
const triviaQuestions = [
  ['Geography', 'What is the capital of Japan?', ['Kyoto', 'Tokyo', 'Osaka', 'Sapporo'], 1],
  ['Geography', 'Which is the largest ocean?', ['Atlantic', 'Indian', 'Arctic', 'Pacific'], 3],
  ['Geography', 'Which country is shaped like a boot?', ['Greece', 'Italy', 'Portugal', 'Croatia'], 1],
  ['Geography', 'What is the capital of Australia?', ['Sydney', 'Melbourne', 'Canberra', 'Perth'], 2],
  ['Geography', 'The River Nile flows into which sea?', ['Red Sea', 'Arabian Sea', 'Mediterranean Sea', 'Black Sea'], 2],
  ['Geography', 'Which is the smallest continent by land area?', ['Europe', 'Australia', 'South America', 'Antarctica'], 1],
  ['Geography', 'Which country has the most people?', ['India', 'United States', 'Indonesia', 'Brazil'], 0],
  ['Geography', 'What is the capital of Canada?', ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'], 2],
  ['Geography', 'Mount Everest is part of which mountain range?', ['Andes', 'Alps', 'Himalayas', 'Rockies'], 2],
  ['Geography', 'Which desert is the largest hot desert?', ['Gobi', 'Sahara', 'Kalahari', 'Arabian'], 1],
  ['Geography', 'Which country is home to the city of Marrakech?', ['Egypt', 'Morocco', 'Tunisia', 'Algeria'], 1],
  ['Geography', 'What is the capital of South Korea?', ['Busan', 'Seoul', 'Incheon', 'Daegu'], 1],
  ['Geography', 'Which US state is known as the Sunshine State?', ['California', 'Texas', 'Florida', 'Arizona'], 2],
  ['Geography', 'Which river runs through London?', ['Severn', 'Thames', 'Trent', 'Clyde'], 1],
  ['Geography', 'Which country has a maple leaf on its flag?', ['Canada', 'Austria', 'Denmark', 'Finland'], 0],
  ['Geography', 'What is the capital of Brazil?', ['Rio de Janeiro', 'Sao Paulo', 'Brasilia', 'Salvador'], 2],
  ['Geography', 'Which is the largest country by land area?', ['China', 'Canada', 'Russia', 'United States'], 2],
  ['Geography', 'Which African country is famous for its pyramids at Giza?', ['Sudan', 'Egypt', 'Libya', 'Ethiopia'], 1],
  ['Geography', 'What is the capital of Spain?', ['Barcelona', 'Seville', 'Madrid', 'Valencia'], 2],
  ['Geography', 'Which island country lies south of India?', ['Maldives', 'Sri Lanka', 'Mauritius', 'Seychelles'], 1],
  ['Science', 'What is the chemical symbol for water?', ['CO2', 'O2', 'H2O', 'NaCl'], 2],
  ['Science', 'Which planet is known as the Red Planet?', ['Venus', 'Mars', 'Jupiter', 'Mercury'], 1],
  ['Science', 'How many legs does a spider have?', ['Six', 'Eight', 'Ten', 'Twelve'], 1],
  ['Science', 'What gas do plants take in from the air?', ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Helium'], 2],
  ['Science', 'What is the center of an atom called?', ['Cell', 'Nucleus', 'Core', 'Orbit'], 1],
  ['Science', 'Which force pulls objects toward Earth?', ['Friction', 'Magnetism', 'Gravity', 'Pressure'], 2],
  ['Science', 'What is the closest star to Earth?', ['Sirius', 'The Sun', 'Proxima Centauri', 'Polaris'], 1],
  ['Science', 'At what temperature does water freeze in Celsius?', ['0 degrees', '10 degrees', '32 degrees', '-10 degrees'], 0],
  ['Science', 'Which part of a plant usually takes in water?', ['Flower', 'Leaf', 'Root', 'Stem'], 2],
  ['Science', 'What is the hardest natural substance?', ['Quartz', 'Diamond', 'Granite', 'Iron'], 1],
  ['Science', 'How many bones are in the adult human body?', ['106', '206', '306', '406'], 1],
  ['Science', 'Which organ pumps blood around the body?', ['Lungs', 'Brain', 'Heart', 'Liver'], 2],
  ['Science', 'What is the boiling point of water at sea level in Celsius?', ['50', '90', '100', '120'], 2],
  ['Science', 'Which planet has the most prominent ring system?', ['Saturn', 'Mars', 'Earth', 'Venus'], 0],
  ['Science', 'What do bees collect from flowers to make honey?', ['Nectar', 'Sap', 'Dew', 'Pollen only'], 0],
  ['Science', 'Which blood cells help fight infection?', ['Red cells', 'White cells', 'Platelets', 'Plasma'], 1],
  ['Science', 'How many chambers does a human heart have?', ['Two', 'Three', 'Four', 'Five'], 2],
  ['Science', 'Which natural material comes from sheep?', ['Cotton', 'Silk', 'Wool', 'Linen'], 2],
  ['Science', 'What is the largest planet in our solar system?', ['Earth', 'Saturn', 'Jupiter', 'Neptune'], 2],
  ['Science', 'Which vitamin is often made in skin from sunlight?', ['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'], 3],
  ['Science', 'What is the process of liquid water turning into vapor?', ['Freezing', 'Condensation', 'Evaporation', 'Melting'], 2],
  ['Science', 'Which animal is a mammal that can fly?', ['Penguin', 'Bat', 'Flying fish', 'Butterfly'], 1],
  ['Science', 'Which instrument measures temperature?', ['Barometer', 'Thermometer', 'Compass', 'Altimeter'], 1],
  ['Science', 'What is the main gas in Earth’s atmosphere?', ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], 2],
  ['Science', 'What is the study of earthquakes called?', ['Ecology', 'Seismology', 'Astronomy', 'Geology'], 1],
  ['Science', 'Which metal is liquid at room temperature?', ['Copper', 'Mercury', 'Aluminium', 'Silver'], 1],
  ['Science', 'What is the largest living animal?', ['African elephant', 'Blue whale', 'Giraffe', 'Whale shark'], 1],
  ['Science', 'What do you call an animal that eats only plants?', ['Carnivore', 'Omnivore', 'Herbivore', 'Insectivore'], 2],
  ['Science', 'Which planet is famous for its Great Red Spot?', ['Jupiter', 'Uranus', 'Mars', 'Neptune'], 0],
  ['Science', 'What is the basic unit of life?', ['Atom', 'Cell', 'Tissue', 'Organ'], 1],
  ['History', 'Who was the first person to walk on the Moon?', ['Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'Michael Collins'], 1],
  ['History', 'The ancient pyramids of Giza are in which country?', ['Mexico', 'Egypt', 'Greece', 'Iraq'], 1],
  ['History', 'Which wall fell in 1989, helping reunite Germany?', ['Hadrian’s Wall', 'Great Wall', 'Berlin Wall', 'Western Wall'], 2],
  ['History', 'Who was the first President of the United States?', ['Abraham Lincoln', 'George Washington', 'John Adams', 'Thomas Jefferson'], 1],
  ['History', 'Which ship sank on its first voyage in 1912?', ['Lusitania', 'Titanic', 'Bismarck', 'Endeavour'], 1],
  ['History', 'Which civilization built Machu Picchu?', ['Maya', 'Aztec', 'Inca', 'Roman'], 2],
  ['History', 'In which country did the Renaissance begin?', ['France', 'Italy', 'England', 'Spain'], 1],
  ['History', 'Who was known as the Maid of Orléans?', ['Cleopatra', 'Joan of Arc', 'Queen Victoria', 'Boudica'], 1],
  ['History', 'Which ancient city was buried by Mount Vesuvius?', ['Athens', 'Pompeii', 'Carthage', 'Sparta'], 1],
  ['History', 'The Great Wall is in which country?', ['Japan', 'China', 'India', 'Mongolia'], 1],
  ['History', 'Who was the first woman to win a Nobel Prize?', ['Ada Lovelace', 'Marie Curie', 'Jane Addams', 'Rosalind Franklin'], 1],
  ['History', 'Which empire was ruled from Rome?', ['Ottoman Empire', 'Roman Empire', 'Mongol Empire', 'Mughal Empire'], 1],
  ['History', 'Who painted the ceiling of the Sistine Chapel?', ['Raphael', 'Donatello', 'Michelangelo', 'Leonardo da Vinci'], 2],
  ['History', 'Which explorer is often credited with reaching the Americas in 1492?', ['Ferdinand Magellan', 'Christopher Columbus', 'James Cook', 'Vasco da Gama'], 1],
  ['History', 'Which Indian leader is associated with non-violent independence protests?', ['Jawaharlal Nehru', 'Mahatma Gandhi', 'Subhas Chandra Bose', 'Sardar Patel'], 1],
  ['History', 'The ancient Olympic Games began in which country?', ['Italy', 'Greece', 'Egypt', 'Turkey'], 1],
  ['History', 'Which queen ruled ancient Egypt and met Julius Caesar?', ['Nefertiti', 'Cleopatra', 'Hatshepsut', 'Arsinoe'], 1],
  ['History', 'What was the name of the first artificial satellite?', ['Apollo 1', 'Sputnik 1', 'Explorer 1', 'Vostok 1'], 1],
  ['History', 'Which city was the first capital of the United States?', ['Boston', 'Philadelphia', 'New York City', 'Washington, D.C.'], 2],
  ['History', 'Which trade route connected China with the Mediterranean?', ['Spice Road', 'Silk Road', 'Amber Road', 'Royal Road'], 1],
  ['Nature', 'What is a group of lions called?', ['Pack', 'Pride', 'Herd', 'Colony'], 1],
  ['Nature', 'Which bird is famous for copying sounds and speech?', ['Eagle', 'Parrot', 'Swan', 'Owl'], 1],
  ['Nature', 'What is the fastest land animal?', ['Lion', 'Horse', 'Cheetah', 'Leopard'], 2],
  ['Nature', 'Which tree produces acorns?', ['Pine', 'Oak', 'Maple', 'Birch'], 1],
  ['Nature', 'What is a baby frog called?', ['Cub', 'Tadpole', 'Calf', 'Nymph'], 1],
  ['Nature', 'Which animal is known for changing its color to blend in?', ['Chameleon', 'Koala', 'Meerkat', 'Panda'], 0],
  ['Nature', 'Which is the tallest animal in the world?', ['Elephant', 'Ostrich', 'Giraffe', 'Camel'], 2],
  ['Nature', 'What do pandas mostly eat?', ['Bamboo', 'Fish', 'Berries', 'Grasshoppers'], 0],
  ['Nature', 'Which sea creature has three hearts?', ['Dolphin', 'Octopus', 'Shark', 'Jellyfish'], 1],
  ['Nature', 'What is the largest type of big cat?', ['Lion', 'Tiger', 'Jaguar', 'Leopard'], 1],
  ['Nature', 'Which insect makes a buzzing sound and produces wax?', ['Ant', 'Bee', 'Cricket', 'Dragonfly'], 1],
  ['Nature', 'What is a baby horse called?', ['Foal', 'Calf', 'Kid', 'Lamb'], 0],
  ['Nature', 'Which animal carries its home on its back?', ['Tortoise', 'Hedgehog', 'Armadillo', 'Snail'], 3],
  ['Nature', 'Which part of a flower often attracts pollinators with color?', ['Petals', 'Roots', 'Stem', 'Thorns'], 0],
  ['Nature', 'What is the name for a scientist who studies fossils?', ['Botanist', 'Paleontologist', 'Meteorologist', 'Zoologist'], 1],
  ['Nature', 'Which animal is known for building dams?', ['Otter', 'Beaver', 'Badger', 'Mink'], 1],
  ['Nature', 'What do you call a home made by a spider?', ['Web', 'Nest', 'Hive', 'Burrow'], 0],
  ['Nature', 'Which mammal lays eggs?', ['Dolphin', 'Platypus', 'Kangaroo', 'Sloth'], 1],
  ['Nature', 'What is the largest species of penguin?', ['Emperor penguin', 'King penguin', 'Little penguin', 'Adelie penguin'], 0],
  ['Nature', 'Which animal has black and white stripes?', ['Zebra', 'Okapi', 'Skunk', 'Badger'], 0],
  ['Culture', 'How many colors are traditionally named in a rainbow?', ['Five', 'Six', 'Seven', 'Eight'], 2],
  ['Culture', 'Which board game uses properties such as Park Place?', ['Clue', 'Monopoly', 'Risk', 'Scrabble'], 1],
  ['Culture', 'What is the name of Harry Potter’s school?', ['Nevermore', 'Hogwarts', 'Rivendell', 'Xavier’s School'], 1],
  ['Culture', 'Which fictional detective lived at 221B Baker Street?', ['Hercule Poirot', 'Sherlock Holmes', 'Nancy Drew', 'Miss Marple'], 1],
  ['Culture', 'In chess, which piece moves in an L shape?', ['Bishop', 'Rook', 'Knight', 'Queen'], 2],
  ['Culture', 'What is the name of the cowboy in Toy Story?', ['Buzz', 'Woody', 'Rex', 'Andy'], 1],
  ['Culture', 'Which sport uses a shuttlecock?', ['Squash', 'Badminton', 'Table tennis', 'Volleyball'], 1],
  ['Culture', 'How many rings are on the Olympic symbol?', ['Four', 'Five', 'Six', 'Seven'], 1],
  ['Culture', 'Which instrument has black and white keys?', ['Violin', 'Piano', 'Flute', 'Trumpet'], 1],
  ['Culture', 'Which game is played with a king, queen, and pawns?', ['Checkers', 'Chess', 'Backgammon', 'Go'], 1],
  ['Culture', 'What is the name of the snowman in Frozen?', ['Sven', 'Olaf', 'Kristoff', 'Marshmallow'], 1],
  ['Culture', 'Which sport is played at Wimbledon?', ['Golf', 'Tennis', 'Cricket', 'Rugby'], 1],
  ['Culture', 'What is the main language spoken in Brazil?', ['Spanish', 'Portuguese', 'French', 'Italian'], 1],
  ['Culture', 'Which superhero is also known as the Dark Knight?', ['Superman', 'Batman', 'Iron Man', 'Spider-Man'], 1],
  ['Culture', 'How many players from one team are on a basketball court?', ['Four', 'Five', 'Six', 'Seven'], 1],
  ['Culture', 'Which fictional land is home to the Shire?', ['Narnia', 'Middle-earth', 'Westeros', 'Oz'], 1],
  ['Culture', 'Which sport has a “hole in one”?', ['Tennis', 'Golf', 'Cricket', 'Baseball'], 1],
  ['Culture', 'What do you call a word that reads the same backward and forward?', ['Anagram', 'Palindrome', 'Synonym', 'Acronym'], 1],
  ['Culture', 'Which card suit is usually shown as a heart shape?', ['Clubs', 'Spades', 'Hearts', 'Diamonds'], 2],
  ['Culture', 'Which month has an extra day in a leap year?', ['January', 'February', 'March', 'December'], 1],
  ['Food', 'Which fruit is dried to make a raisin?', ['Plum', 'Grape', 'Cherry', 'Fig'], 1],
  ['Food', 'What is the main ingredient in guacamole?', ['Avocado', 'Cucumber', 'Peas', 'Zucchini'], 0],
  ['Food', 'Sushi is most closely associated with which country?', ['Thailand', 'Japan', 'Vietnam', 'Korea'], 1],
  ['Food', 'Which spice gives many curries a bright yellow color?', ['Cinnamon', 'Turmeric', 'Paprika', 'Nutmeg'], 1],
  ['Food', 'What type of food is a Brie?', ['Bread', 'Cheese', 'Fruit', 'Pasta'], 1],
  ['Food', 'Which drink is made by steeping tea leaves?', ['Lemonade', 'Tea', 'Cider', 'Cocoa'], 1],
  ['Food', 'What is the main ingredient in hummus?', ['Lentils', 'Chickpeas', 'Kidney beans', 'Peanuts'], 1],
  ['Food', 'Which grain is used to make traditional popcorn?', ['Rice', 'Wheat', 'Corn', 'Oats'], 2],
  ['Food', 'Which fruit is known for having seeds on its outside?', ['Raspberry', 'Strawberry', 'Blueberry', 'Blackberry'], 1],
  ['Food', 'What is tofu primarily made from?', ['Soybeans', 'Rice', 'Potatoes', 'Almonds'], 0],
  ['Food', 'Which pasta shape looks like a small tube?', ['Penne', 'Farfalle', 'Orzo', 'Fusilli'], 0],
  ['Food', 'What is the main ingredient in traditional pesto?', ['Basil', 'Mint', 'Parsley', 'Spinach'], 0],
  ['Food', 'Which fruit is traditionally used in a key lime pie?', ['Lemon', 'Lime', 'Orange', 'Grapefruit'], 1],
  ['Food', 'What kind of food is a samosa?', ['Filled pastry', 'Noodle soup', 'Flatbread', 'Rice cake'], 0],
  ['Food', 'Maple syrup is made from the sap of which tree?', ['Oak', 'Maple', 'Pine', 'Willow'], 1],
  ['Food', 'Which nut is used to make marzipan?', ['Walnut', 'Almond', 'Hazelnut', 'Pistachio'], 1],
  ['Food', 'What is the main ingredient in traditional miso soup?', ['Miso paste', 'Tomato', 'Coconut milk', 'Cream'], 0],
  ['Food', 'Which fruit is a key ingredient in a classic banana split?', ['Apple', 'Banana', 'Pear', 'Peach'], 1],
  ['Food', 'Which country is especially associated with croissants?', ['France', 'Germany', 'Greece', 'Sweden'], 0],
  ['Food', 'What is the name for coffee made by forcing hot water through grounds?', ['Espresso', 'Mocha', 'Latte', 'Americano'], 0],
  ['Quick Facts', 'How many days are in a standard year?', ['364', '365', '366', '367'], 1],
  ['Quick Facts', 'How many sides does a hexagon have?', ['Five', 'Six', 'Seven', 'Eight'], 1],
  ['Quick Facts', 'What is 9 multiplied by 7?', ['56', '63', '72', '79'], 1],
  ['Quick Facts', 'How many minutes are in one hour?', ['30', '45', '60', '90'], 2],
  ['Quick Facts', 'Which shape has three sides?', ['Square', 'Triangle', 'Pentagon', 'Circle'], 1],
  ['Quick Facts', 'What is the Roman numeral for 10?', ['V', 'X', 'L', 'C'], 1],
  ['Quick Facts', 'How many letters are in the English alphabet?', ['24', '25', '26', '27'], 2],
  ['Quick Facts', 'What is half of 100?', ['25', '40', '50', '60'], 2],
  ['Quick Facts', 'Which day comes after Friday?', ['Thursday', 'Saturday', 'Sunday', 'Monday'], 1],
  ['Quick Facts', 'How many months have 31 days?', ['Five', 'Six', 'Seven', 'Eight'], 2],
  ['Quick Facts', 'Which direction does the Sun appear to rise from?', ['North', 'South', 'East', 'West'], 2],
  ['Quick Facts', 'What is the opposite of “ancient”?', ['Old', 'Modern', 'Historic', 'Former'], 1],
  ['Quick Facts', 'What is the square root of 81?', ['7', '8', '9', '10'], 2],
  ['Quick Facts', 'How many zeros are in one thousand?', ['Two', 'Three', 'Four', 'Five'], 1],
  ['Quick Facts', 'Which is the longest day of the week in its English spelling?', ['Wednesday', 'Thursday', 'Saturday', 'Tuesday'], 0],
  ['Quick Facts', 'What do you call a shape with eight sides?', ['Hexagon', 'Heptagon', 'Octagon', 'Nonagon'], 2],
  ['Quick Facts', 'Which month comes directly before October?', ['August', 'September', 'November', 'July'], 1],
  ['Quick Facts', 'How many degrees are in a right angle?', ['45', '90', '180', '360'], 1],
  ['Quick Facts', 'What is the plural of “mouse”?', ['Mouses', 'Meese', 'Mice', 'Mouse'], 2],
  ['Quick Facts', 'Which tool is used to find north?', ['Thermometer', 'Compass', 'Ruler', 'Clock'], 1],
];

module.exports = triviaQuestions.map(([category, prompt, options, answerIndex], index) => ({
  id: `trivia-${index + 1}`,
  category,
  difficulty: 'easy',
  prompt,
  options,
  answerIndex,
})).concat(
  require('./triviaExtraQuestions'),
  require('./triviaMoreQuestions'),
  require('./triviaMegaQuestions'),
  require('./triviaUltraQuestions')
);
