const rows = [
  // GEOGRAPHY · MEDIUM
  ['Geography','medium','Which European capital stands on the River Danube?','Vienna|Madrid|Lisbon|Oslo',0],
  ['Geography','medium','Which country contains the region of Transylvania?','Romania|Bulgaria|Hungary|Serbia',0],
  ['Geography','medium','What is the capital of New Zealand?','Auckland|Wellington|Christchurch|Hamilton',1],
  ['Geography','medium','Which African lake is the world’s largest tropical lake by area?','Lake Tanganyika|Lake Victoria|Lake Malawi|Lake Chad',1],
  ['Geography','medium','Which country has the cities of Osaka and Kyoto?','China|Japan|South Korea|Thailand',1],
  ['Geography','medium','Which mountain range separates France and Spain?','Pyrenees|Carpathians|Apennines|Caucasus',0],
  ['Geography','medium','What is the capital of Kenya?','Nairobi|Lagos|Kampala|Kigali',0],
  ['Geography','medium','Which sea lies between Saudi Arabia and Africa?','Black Sea|Red Sea|Caspian Sea|Baltic Sea',1],
  ['Geography','medium','Which country is also known as the Netherlands?','Holland|Belgium|Luxembourg|Denmark',0],
  ['Geography','medium','Which US state is made up entirely of islands in the Pacific?','Alaska|Hawaii|Rhode Island|Florida',1],
  // GEOGRAPHY · DIFFICULT
  ['Geography','difficult','Which strait separates the island of Tasmania from mainland Australia?','Bass Strait|Torres Strait|Cook Strait|Bering Strait',0],
  ['Geography','difficult','What is the capital of Bhutan?','Thimphu|Kathmandu|Paro|Dhaka',0],
  ['Geography','difficult','Which river flows through Baghdad?','Euphrates|Tigris|Jordan|Orontes',1],
  ['Geography','difficult','Which country borders both the Caspian Sea and the Persian Gulf?','Iran|Iraq|Azerbaijan|Turkmenistan',0],
  ['Geography','difficult','Which is the world’s highest uninterrupted waterfall?','Angel Falls|Victoria Falls|Iguazu Falls|Yosemite Falls',0],
  ['Geography','difficult','Which desert covers much of Botswana and Namibia?','Sahara|Kalahari|Namib|Danakil',1],
  ['Geography','difficult','What is the capital of Kyrgyzstan?','Dushanbe|Bishkek|Tashkent|Ashgabat',1],
  ['Geography','difficult','Which island is shared by Haiti and the Dominican Republic?','Jamaica|Hispaniola|Cuba|Puerto Rico',1],
  ['Geography','difficult','Which country has the longest coastline in the world?','Russia|Canada|Indonesia|Norway',1],
  ['Geography','difficult','Which sea is the saltiest large body of water?','Dead Sea|Baltic Sea|North Sea|Black Sea',0],

  // HISTORY · MEDIUM
  ['History','medium','Which ancient civilization used cuneiform writing?','Sumerians|Vikings|Incas|Phoenicians',0],
  ['History','medium','Who was the first emperor of Rome?','Julius Caesar|Augustus|Nero|Trajan',1],
  ['History','medium','The Magna Carta was sealed in which year?','1066|1215|1492|1776',1],
  ['History','medium','Which ancient people built the city of Petra?','Nabataeans|Minoans|Etruscans|Hittites',0],
  ['History','medium','Who was the first Mughal emperor in India?','Akbar|Babur|Humayun|Shah Jahan',1],
  ['History','medium','Which city was divided by a wall during the Cold War?','Vienna|Berlin|Prague|Warsaw',1],
  ['History','medium','Which explorer led the first expedition to circumnavigate the globe?','James Cook|Ferdinand Magellan|Francis Drake|Marco Polo',1],
  ['History','medium','Which civilization built the city of Tenochtitlan?','Aztec|Inca|Maya|Olmec',0],
  ['History','medium','Who was the British prime minister for most of World War II?','Neville Chamberlain|Winston Churchill|Clement Attlee|Anthony Eden',1],
  ['History','medium','Which empire built the road network centered on Cusco?','Roman|Inca|Mongol|Persian',1],
  // HISTORY · DIFFICULT
  ['History','difficult','Which English king was forced to sign the Magna Carta?','Henry II|John|Richard I|Edward I',1],
  ['History','difficult','The Rosetta Stone helped scholars decode which script?','Cuneiform|Egyptian hieroglyphs|Linear B|Sanskrit',1],
  ['History','difficult','Which dynasty built most of Beijing’s Forbidden City?','Ming|Tang|Qing|Song',0],
  ['History','difficult','Which 1648 settlement ended the Thirty Years’ War?','Peace of Westphalia|Treaty of Tordesillas|Congress of Vienna|Peace of Augsburg',0],
  ['History','difficult','Who founded the Maurya Empire in ancient India?','Ashoka|Chandragupta Maurya|Bindusara|Harsha',1],
  ['History','difficult','Which battle in 1066 led to Norman rule in England?','Battle of Hastings|Battle of Agincourt|Battle of Bosworth|Battle of Crécy',0],
  ['History','difficult','What was the capital of the Byzantine Empire?','Antioch|Constantinople|Alexandria|Athens',1],
  ['History','difficult','Which queen led a revolt against Roman rule in ancient Britain?','Boudica|Eleanor of Aquitaine|Matilda|Elizabeth I',0],
  ['History','difficult','Who was the first woman to rule Egypt as pharaoh in her own right?','Nefertiti|Hatshepsut|Cleopatra VII|Merneith',1],
  ['History','difficult','Which treaty divided newly encountered lands between Spain and Portugal in 1494?','Treaty of Tordesillas|Treaty of Utrecht|Treaty of Paris|Treaty of Zaragoza',0],

  // NATURE · MEDIUM
  ['Nature','medium','What is the only mammal capable of true sustained flight?','Flying squirrel|Bat|Sugar glider|Colugo',1],
  ['Nature','medium','What is a group of crows commonly called?','Murder|Parliament|Drove|School',0],
  ['Nature','medium','Which animal has the longest migration of any mammal?','Gray whale|Caribou|Humpback whale|Elephant seal',2],
  ['Nature','medium','What is the name for a plant that grows on another plant without taking its nutrients?','Epiphyte|Parasite|Carnivore|Succulent',0],
  ['Nature','medium','Which bear species is native to the Arctic?','Sun bear|Polar bear|Spectacled bear|Sloth bear',1],
  ['Nature','medium','What is the largest species of turtle?','Green sea turtle|Leatherback sea turtle|Loggerhead turtle|Aldabra tortoise',1],
  ['Nature','medium','Which animal uses echolocation to find prey underwater?','Dolphin|Manatee|Sea turtle|Walrus',0],
  ['Nature','medium','What is the name for an animal active mostly at dawn and dusk?','Nocturnal|Diurnal|Crepuscular|Arboreal',2],
  ['Nature','medium','Which tree is famous for its white bark and peeling layers?','Birch|Cedar|Redwood|Cypress',0],
  ['Nature','medium','What do monarch butterflies store from milkweed that makes them taste bad to predators?','Alkaloids|Cardiac glycosides|Caffeine|Tannins',1],
  // NATURE · DIFFICULT
  ['Nature','difficult','What is the largest living species of lizard?','Komodo dragon|Nile monitor|Gila monster|Green iguana',0],
  ['Nature','difficult','Which bird has the largest wingspan of any living bird?','Wandering albatross|Andean condor|Golden eagle|Mute swan',0],
  ['Nature','difficult','What is the name for animals that are most active at night?','Diurnal|Nocturnal|Crepuscular|Sessile',1],
  ['Nature','difficult','Which mammal has the longest gestation period?','African elephant|Blue whale|Giraffe|Rhinoceros',0],
  ['Nature','difficult','What is the world’s largest living coral reef system?','Great Barrier Reef|Belize Barrier Reef|New Caledonia Reef|Red Sea Reef',0],
  ['Nature','difficult','Which tree produces the largest edible fruit that grows on a tree?','Jackfruit tree|Baobab|Mango tree|Coconut palm',0],
  ['Nature','difficult','What is the scientific name for the fearsome “immortal jellyfish”?','Turritopsis dohrnii|Aurelia aurita|Chironex fleckeri|Cyanea capillata',0],
  ['Nature','difficult','Which animal is known to have fingerprints remarkably similar to humans?','Koala|Panda|Lemur|Raccoon',0],
  ['Nature','difficult','What is the term for a species found naturally in only one geographic area?','Invasive|Endemic|Migratory|Cosmopolitan',1],
  ['Nature','difficult','Which is the largest living species of penguin?','Emperor penguin|King penguin|Gentoo penguin|Macaroni penguin',0],

  // CULTURE · MEDIUM
  ['Culture','medium','In chess, which piece can jump over other pieces?','Bishop|Knight|Rook|Queen',1],
  ['Culture','medium','Which language has the most native speakers worldwide?','English|Mandarin Chinese|Spanish|Hindi',1],
  ['Culture','medium','What is the traditional Japanese art of paper folding called?','Origami|Ikebana|Bonsai|Sumi-e',0],
  ['Culture','medium','Which country is credited with inventing paper?','India|China|Egypt|Greece',1],
  ['Culture','medium','What is the name of the traditional Scottish skirt?','Kimono|Kilt|Sarong|Toga',1],
  ['Culture','medium','Which sport uses the terms “love” and “deuce”?','Badminton|Tennis|Squash|Table tennis',1],
  ['Culture','medium','How many strings does a standard violin have?','Four|Five|Six|Seven',0],
  ['Culture','medium','Which board game features the detective Miss Scarlett?','Risk|Cluedo|Monopoly|Catan',1],
  ['Culture','medium','What is the name of the award given by the Academy of Motion Picture Arts and Sciences?','Grammy|Oscar|Tony|Emmy',1],
  ['Culture','medium','Which dance style originated in Argentina and Uruguay?','Samba|Tango|Flamenco|Salsa',1],
  // CULTURE · DIFFICULT
  ['Culture','difficult','Which language family includes Finnish and Hungarian?','Romance|Uralic|Germanic|Slavic',1],
  ['Culture','difficult','What is the Japanese tea ceremony commonly called?','Chanoyu|Kabuki|Hanami|Shodo',0],
  ['Culture','difficult','Which architect designed the Guggenheim Museum in Bilbao?','Frank Gehry|Zaha Hadid|I. M. Pei|Renzo Piano',0],
  ['Culture','difficult','Which ancient Greek poet is traditionally credited with The Iliad?','Hesiod|Homer|Sophocles|Pindar',1],
  ['Culture','difficult','What is the name of the traditional Indian classical dance from Tamil Nadu?','Kathak|Bharatanatyam|Odissi|Manipuri',1],
  ['Culture','difficult','Which art movement is associated with Claude Monet?','Cubism|Impressionism|Surrealism|Futurism',1],
  ['Culture','difficult','Which playwright wrote Waiting for Godot?','Samuel Beckett|Harold Pinter|Oscar Wilde|Arthur Miller',0],
  ['Culture','difficult','What is the name of the Japanese woodblock-print style associated with Hokusai?','Ukiyo-e|Sumi-e|Nihonga|Kintsugi',0],
  ['Culture','difficult','Which civilization created the Nazca Lines?','Nazca|Moche|Chavín|Tiwanaku',0],
  ['Culture','difficult','Which literary character is the narrator of Moby-Dick?','Captain Ahab|Ishmael|Queequeg|Starbuck',1],

  // FOOD · MEDIUM
  ['Food','medium','Which cheese is traditionally used in a Greek salad?','Feta|Gouda|Brie|Cheddar',0],
  ['Food','medium','What is the main ingredient in traditional falafel?','Chickpeas|Potatoes|Lentils|Rice',0],
  ['Food','medium','Which Italian dessert is made with layers of coffee-soaked biscuits and cream?','Tiramisu|Panna cotta|Cannoli|Gelato',0],
  ['Food','medium','What is the main ingredient in kimchi?','Fermented vegetables|Rice noodles|Tofu|Seaweed',0],
  ['Food','medium','Which nut is traditionally used in pesto alla Genovese?','Pine nut|Cashew|Peanut|Macadamia',0],
  ['Food','medium','What is the name of the Japanese soup made with miso paste?','Miso soup|Pho|Ramen broth|Dashi curry',0],
  ['Food','medium','Which grain is used to make risotto?','Arborio rice|Couscous|Quinoa|Barley',0],
  ['Food','medium','What is paneer?','A fresh cheese|A flatbread|A lentil stew|A spice mix',0],
  ['Food','medium','Which herb is the main flavor in traditional tabbouleh?','Parsley|Dill|Rosemary|Sage',0],
  ['Food','medium','Which fruit is used to make traditional cider?','Apple|Pear|Grape|Plum',0],
  // FOOD · DIFFICULT
  ['Food','difficult','Which traditional Japanese food is made from fermented soybeans and known for its sticky texture?','Natto|Mirin|Ponzu|Dashi',0],
  ['Food','difficult','What is the French cooking term for ingredients prepared and arranged before cooking?','Mise en place|Sous vide|À la carte|Flambé',0],
  ['Food','difficult','Which Italian rice variety is especially associated with risotto?','Arborio|Basmati|Jasmine|Sushi rice',0],
  ['Food','difficult','What gives blue cheese its characteristic blue veins?','Penicillium mold|Lactic yeast|Blue algae|Juniper ash',0],
  ['Food','difficult','Which spice is made from the dried stigmas of a crocus flower?','Saffron|Turmeric|Cardamom|Sumac',0],
  ['Food','difficult','What is the primary grain in traditional Ethiopian injera?','Teff|Millet|Sorghum|Barley',0],
  ['Food','difficult','Which region is most closely associated with Parmigiano Reggiano?','Emilia-Romagna|Tuscany|Sicily|Lazio',0],
  ['Food','difficult','What is the name of the Japanese fermented soybean paste used in soup?','Miso|Shoyu|Mirin|Yuzu',0],
  ['Food','difficult','Which French sauce is traditionally made from egg yolks and clarified butter?','Hollandaise|Béchamel|Velouté|Roux',0],
  ['Food','difficult','What is the main ingredient in the Middle Eastern dip baba ganoush?','Eggplant|Chickpeas|Yogurt|Beetroot',0],

  // QUICK FACTS · MEDIUM
  ['Quick Facts','medium','What is the Roman numeral for 50?','L|C|D|M',0],
  ['Quick Facts','medium','How many degrees are in the interior angles of a triangle in total?','90|180|270|360',1],
  ['Quick Facts','medium','Which unit is equal to one thousand meters?','Kilometer|Centimeter|Mile|Hectare',0],
  ['Quick Facts','medium','How many hours are in two days?','24|36|48|60',2],
  ['Quick Facts','medium','What is the next prime number after 7?','9|10|11|13',2],
  ['Quick Facts','medium','How many letters are in the Greek alphabet?','22|24|26|28',1],
  ['Quick Facts','medium','Which month has 28 days in a common year?','February|All of them|January|April',1],
  ['Quick Facts','medium','What is 12 squared?','124|132|144|156',2],
  ['Quick Facts','medium','How many minutes are in a quarter of an hour?','10|15|20|25',1],
  ['Quick Facts','medium','What is the name for a word formed from the first letters of a phrase?','Acronym|Palindrome|Synonym|Homonym',0],
  // QUICK FACTS · DIFFICULT
  ['Quick Facts','difficult','What is the smallest prime number greater than 100?','101|103|107|109',0],
  ['Quick Facts','difficult','How many sides does a dodecagon have?','10|12|14|20',1],
  ['Quick Facts','difficult','What is the Roman numeral for 900?','CM|XM|DM|LM',0],
  ['Quick Facts','difficult','What is the sum of the interior angles of a hexagon?','540°|600°|720°|900°',2],
  ['Quick Facts','difficult','How many bits are in one byte?','4|8|16|32',1],
  ['Quick Facts','difficult','Which number is represented by the binary value 1010?','8|9|10|12',2],
  ['Quick Facts','difficult','What is the only even prime number?','0|1|2|4',2],
  ['Quick Facts','difficult','How many edges does a cube have?','8|10|12|14',2],
  ['Quick Facts','difficult','What is the value of pi rounded to two decimal places?','3.12|3.14|3.16|3.18',1],
  ['Quick Facts','difficult','How many seconds are in one hour?','600|1800|3600|7200',2],
];

module.exports = rows.map(([category, difficulty, prompt, choices, answerIndex], index) => ({
  id: `more-${index + 1}`,
  category,
  difficulty,
  prompt,
  options: choices.split('|'),
  answerIndex,
}));
